language: ruby
matrix:
  include:
    - rvm: jruby-9k
      jdk: oraclejdk8
      before-install: gem install bundler --no-ri --no-rdoc
    - rvm: jruby-9k
      jdk: openjdk8
      before-install: gem install bundler --no-ri --no-rdoc

# For OpenJDK 8 support
# https://github.com/travis-ci/travis-ci/issues/2968
dist: trusty

addons:
  # Fix OpenJDK builds
  # https://github.com/travis-ci/travis-ci/issues/5227
  hostname: short-hostname
